language: node_js

node_js:
  - '0.10'

before_install:
  - gem install sass compass
  - sass --version

before_script:
  - chmod +x .travis/after_success.sh

script:
  - gulp --require LiveScript build

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:g0v/env.g0v.tw"
    - secure: "Gvn6EepSj0rDu45Az95Pq9Ct4Q8Iqgvl3xBHjaNjmdfp+lfYY3cJz7nRzE1NG+koK1xVX811gvpek7oTpiIxtIQrxJAPDDtQUYzfio6MX/u4SAGKIxlW9hDASpRY3i/GbQQmGdJdA9lZCoMqmAvqaxSrEayXTet7y5J+w7HgmPQ="

after_success: .travis/after_success.sh
